CREATE DATABASE tfg;

USE tfg;

CREATE TABLE USER (
COD_USER BIGINT NOT NULL AUTO_INCREMENT,
USERNAME VARCHAR(255) NOT NULL UNIQUE,
PASS VARBINARY(255) NOT NULL,
EMAIL VARCHAR(255) NOT NULL UNIQUE,
PRIMARY KEY (COD_USER)
);


CREATE TABLE GAME (
COD_GAME BIGINT NOT NULL AUTO_INCREMENT,
TITTLE VARCHAR(255),
INTRO VARCHAR(255),
LOGO LONGBLOB,
COD_USER BIGINT NOT NULL,
PRIMARY KEY (COD_GAME),
FOREIGN KEY (COD_USER) REFERENCES USER(COD_USER)
);

CREATE TABLE STORY (
COD_STORY BIGINT NOT NULL AUTO_INCREMENT,
TITTLE VARCHAR(255),
DESCRIPTION VARCHAR(255),
COD_GAME BIGINT NOT NULL,
PRIMARY KEY (COD_STORY),
FOREIGN KEY (COD_GAME) REFERENCES GAME(COD_GAME)
);

CREATE TABLE RACE (
COD_RACE BIGINT NOT NULL AUTO_INCREMENT,
MOVEMENT INT,
NAME VARCHAR(255),
PRIMARY KEY (COD_RACE)
);

CREATE TABLE CLASS (
COD_CLASS BIGINT NOT NULL AUTO_INCREMENT,
DA CHAR(4),
NAME VARCHAR(255),
PRIMARY KEY (COD_CLASS)
);

CREATE TABLE ADVLVL(
COD_ADVLVL BIGINT NOT NULL AUTO_INCREMENT,
LVL INT,
ATQ INT,
POD INT,
INS INT,
COD_CLASS BIGINT NOT NULL,
PRIMARY KEY (COD_ADVLVL),
FOREIGN KEY (COD_CLASS) REFERENCES CLASS(COD_CLASS)
);

CREATE TABLE PJ(
COD_PJ BIGINT NOT NULL AUTO_INCREMENT,
NAME VARCHAR(255),
LEVEL INT,
XP INT,
ALERT INT,
COMMUNICATION INT,
MANIPULATION INT,
ERUDITION INT,
SUBTERFUGE INT,
SURVIVAL INT,
MOVEMENT INT,
PV INT,
DEFENSE INT,
ATTACK INT,
INSTINCT INT,
POWER INT,
STRENGTH INT,
DEXTERITY INT,
CONSTITUTION INT,
INTELLIGENCE INT,
WISDOM INT,
CHARISMA INT,
BACKGROUND TEXT,
COD_USER BIGINT NOT NULL,
COD_GAME BIGINT,
COD_RACE BIGINT NOT NULL,
COD_CLASS BIGINT NOT NULL,
PRIMARY KEY (COD_PJ),
FOREIGN KEY (COD_USER) REFERENCES USER(COD_USER),
FOREIGN KEY (COD_GAME) REFERENCES GAME(COD_GAME),
FOREIGN KEY (COD_RACE) REFERENCES RACE(COD_RACE),
FOREIGN KEY (COD_CLASS) REFERENCES CLASS(COD_CLASS)
);

CREATE TABLE TALENT (
COD_TALENT BIGINT NOT NULL AUTO_INCREMENT,
DESCRIPTION TEXT,
NAME VARCHAR(255),
PRIMARY KEY (COD_TALENT)
);

CREATE TABLE RACE_TALENT (
COD_RACE BIGINT,
COD_TALENT BIGINT,
PRIMARY KEY (COD_RACE,COD_TALENT),
FOREIGN KEY (COD_RACE) REFERENCES RACE(COD_RACE),
FOREIGN KEY (COD_TALENT) REFERENCES TALENT(COD_TALENT)
);

CREATE TABLE CLASS_TALENT (
COD_CLASS BIGINT,
COD_TALENT BIGINT,
PRIMARY KEY (COD_CLASS,COD_TALENT),
FOREIGN KEY (COD_CLASS) REFERENCES CLASS(COD_CLASS),
FOREIGN KEY (COD_TALENT) REFERENCES TALENT(COD_TALENT)
);

CREATE TABLE EQUIPMENT(
COD_EQUIPMENT BIGINT NOT NULL AUTO_INCREMENT,
NAME VARCHAR(255),
PRICE VARCHAR(255),
PRIMARY KEY (COD_EQUIPMENT)
);

CREATE TABLE PJ_EQUIPMENT (
COD_EQUIPMENT BIGINT,
COD_PJ BIGINT,
PRIMARY KEY(COD_EQUIPMENT,COD_PJ),
FOREIGN KEY(COD_EQUIPMENT) REFERENCES EQUIPMENT(COD_EQUIPMENT),
FOREIGN KEY (COD_PJ) REFERENCES PJ(COD_PJ)
);

CREATE TABLE ARMOR (
COD_EQUIPMENT BIGINT,
DEFENSE INT,
PRIMARY KEY (COD_EQUIPMENT),
FOREIGN KEY (COD_EQUIPMENT) REFERENCES EQUIPMENT(COD_EQUIPMENT)
);

CREATE TABLE WEAPON (
COD_EQUIPMENT BIGINT,
DAMAGE VARCHAR(255),
PRIMARY KEY (COD_EQUIPMENT),
FOREIGN KEY (COD_EQUIPMENT) REFERENCES EQUIPMENT(COD_EQUIPMENT)
);

CREATE TABLE RANGED (
COD_EQUIPMENT BIGINT,
SHOTS INT,
RANG VARCHAR(255),
PRIMARY KEY (COD_EQUIPMENT),
FOREIGN KEY (COD_EQUIPMENT) REFERENCES EQUIPMENT(COD_EQUIPMENT)
);


