SELECT EQUIPMENT.COD_EQUIPMENT,EQUIPMENT.NAME, EQUIPMENT.PRICE, WEAPON.DAMAGE, RANGED.RANG, RANGED.SHOTS
FROM ((EQUIPMENT
INNER JOIN WEAPON ON EQUIPMENT.COD_EQUIPMENT = WEAPON.COD_EQUIPMENT)
INNER JOIN RANGED ON RANGED.COD_EQUIPMENT = EQUIPMENT.COD_EQUIPMENT);

SELECT RACE.COD_RACE, RACE.NAME, TALENT.NAME, TALENT.DESCRIPTION
FROM ((RACE
INNER JOIN RACE_TALENT ON RACE.COD_RACE = RACE_TALENT.COD_RACE)
INNER JOIN TALENT ON RACE_TALENT.COD_TALENT = TALENT.COD_TALENT);

SELECT CLASS.COD_CLASS, CLASS.NAME, TALENT.NAME, TALENT.DESCRIPTION
FROM ((CLASS
INNER JOIN CLASS_TALENT ON CLASS.COD_CLASS = CLASS_TALENT.COD_CLASS)
INNER JOIN TALENT ON CLASS_TALENT.COD_TALENT = TALENT.COD_TALENT);
